name: phys549
channels:
  - conda-forge
dependencies:
  - numpy
  - tensorflow
  - scikit-learn
  - py-xgboost
  - uproot
  - awkward
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - notebook
  - tqdm
